### ISSUE TITLE
not working inside scrollers widgets

### ISSUE THREAD

**Issue by abdalmonem** [superlistapp/super_native_extensions#140]
hello , our team is really appreciate for your plugin
we had an issue , when you use `ContextMenuWidget` on any scroll-able widgets 'listview, listview.builder ... ect' , the context menu is not working

tested on:
device : 'Iphone x & Iphone 13'
OS: 'IOS 16.3.1 & IOS 16.3.0 '

test code:

`Scaffold(
      body: ListView(
        children: [
          Container(
            child: ContextMenuWidget(
              child: const SizedBox(
                width: 200,
                height: 200,
                child: Text('Basefdf Context Menu'),
              ),
              menuProvider: (_) {
                return Menu(
                  children: [
                    MenuAction(title: 'Menu Item 2', callback: () {}),
                    MenuAction(title: 'Menu Item 3', callback: () {}),
                  ],
                );
              },
            ),
          ),
          Container(
            child: ContextMenuWidget(
              child: const SizedBox(
                width: 200,
                height: 200,
                child: Text('Basefdf Context Menu'),
              ),
              menuProvider: (_) {
                return Menu(
                  children: [
                    MenuAction(title: 'Menu Item 2', callback: () {}),
                    MenuAction(title: 'Menu Item 3', callback: () {}),
                  ],
                );
              },
            ),
          )
        ],
      ),
    )`

**Comment by knopp** [comment]
Thanks for the report. This happens because list view has pan gesture detector that gets recognized immediately and setting ignorePointer on the listView, which prevent context menu from getting the hitTest.

This will be fixed in next update. In the meanwhile, you can wrap the context menu in a simple `GestureDetector` widget with empty `onTap`, like this:

```dart
GestureDetector(          
  behavior: HitTestBehavior.opaque,
  onTap: () {},
  child: ContextMenuWidget(...
```
This will delay the ignore pointer until user actually starts dragging, which will allow the context menu to work.

**Comment by abdalmonem** [comment]
@knopp 
its works now , thanks for your fast response

**Comment by abdalmonem** [comment]
@knopp  i have a question , is there any way to remove IOS blur area ?
![IMG_29C712672AFA-1](https://github.com/superlistapp/super_native_extensions/assets/9139030/a53dea70-61af-4008-9222-df2218259930)
we try to make some thing like this

**Comment by abdalmonem** [comment]
i try to override : `DefaultMobileMenuWidgetBuilder`
and use it in `mobileMenuWidgetBuilder` , but didnt work

`class _MenuBuilder extends DefaultMobileMenuWidgetBuilder{
  @override
  Widget buildOverlayBackground(BuildContext context, double opacity) {
    return Container(
      width: 300,
      height: 300,
      color: Colors.yellow,
    );
  }
}
`

**Comment by knopp** [comment]
You can't remove the blur in Flutter because the context menu on iOS is native context menu and the blur is native iOS blur.

The context menu in super_native_extensions is different kind than the one on your screenshot - it is triggered by long press and supports transition to drag & drop, in which case there is always blur on iOS. 

In your example that is a button menu, which is different kind of menu and is currently not implemented in super_native_extensions.

**Comment by abdalmonem** [comment]
Thanks for this informations

**Comment by f-person** [comment]
> This will be fixed in next update

@knopp I think it'd be better to keep this issue open for others to find the temporary fix easier and be able to subscribe to status updates and get a notification when it's closed for good :)
