### ISSUE TITLE
Cannot use homebrew-installed Rust

### ISSUE THREAD

**Issue by gspencergoog** [superlistapp/super_native_extensions#181]
On macOS, the build process depends on `rustup`, so it can't use any other Rust installation.

If I try to install `rustup` while Rust is installed by Homebrew, it gives a scary warning, and won't install.

Ideally, the build would recognize that there already is a `rustc` available at an acceptable version and just use whatever was found.

**Comment by knopp** [comment]
Hey! First of all, I made a decent progress on prebuilt binaries :) Hoping to have a pre-prerelease version published in few days.

I tried first installing rust through homebrew and then through rustup, it did give a warning but it let me install it anyway after confirmation.

Unfortunately we can't just use any rustc. Rustup is required because it can install additional targets necessary for cross compiling. The homebrew Rust can only compile to host platform, which is quite useless for Flutter.

In next update the whole build will be driven by Dart. So we can be more flexible about the Rust check, when Rust is needed. So we can for example detect homebrew Rust, and suggest doing 

```sh
brew unlink rust
```

first. Which removes homebrew rust from PATH (while keeping it installed) and the rustup installer won't complain anymore.

We could also suggest installing Rust through

```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | RUSTUP_INIT_SKIP_PATH_CHECK=yes sh
```

but I think `brew unlink rust` is the correct solution.

**Comment by gspencergoog** [comment]
> Hey! First of all, I made a decent progress on prebuilt binaries :) Hoping to have a pre-prerelease version published in few days.

Excellent!

Okay, so this issue really mostly a documentation change then, that's good, although it's too bad we can't just use an existing Rust install. Is there a way to configure the `rustup` location with an env var? Then the user could just set that instead of having to include it in their PATH, or uninstall/unlink their existing install. Although I suppose PATH could be that environment variable, and they could just modify that before running the app without setting it in their shell.

Does this also mean that we'll need to have a Dart package for each of the Rust dependencies in use, once we have the ability to depend on "external" packages? It would be nice if the end state were that the user doesn't need to think about Rust at all when depending on the package. I suppose it depends on whether the pub solution allows making a package out of `rustup` or not.

**Comment by knopp** [comment]
This should be already fixed in cargokit.
