### ISSUE TITLE
Super clipboard should provide path instead of direct file in binary

### ISSUE THREAD

**Issue by alihassan143** [superlistapp/super_native_extensions#229]

**Comment by knopp** [comment]
Can you be more specific?

**Comment by alihassan143** [comment]
@knopp  if i use the super clipboard it provide file in Uni8list format that is binary format instead of that it should provide directly file path like 
[Desktop Drop](https://pub.dev/packages/desktop_drop) package

**Comment by knopp** [comment]
If there is file path in the clipboard (or drag & drop payload) you can access it through `reader.getValue(Formats.fileUri, ...)`. The plugin will not hide it from you. However reading the actual content is better approach because it will work in situations where there is no file URI, for example when receiving virtual files (file promises), on web, android, and iOS.

**Comment by alihassan143** [comment]
@knopp  let me try

**Comment by alihassan143** [comment]
@knopp  i can get the value but how i can get all files path?

**Comment by alihassan143** [comment]
everything working great as expected thanks
