### ISSUE TITLE
Plain text  format on Mac-os should also support plain non utf8 text

### ISSUE THREAD

**Issue by remonh87** [superlistapp/super_native_extensions#73]
First of all great package and thank you for open sourcing it! 

I ran into a small issue. When I drag in  a simple text file it happens that the Format is not be considered format.plaintext while my assumption is that it should be.

How to reproduce (I reproduced it on macOS Ventura):
1. Drag file test.text into a DropRegion
2. On perform drop retrieve the platform format and notice it gets `[public.file-url, com.apple.finder.node, public.plain-text]`

Expected behaviour: I would suspect this file to be a plaintext format. I already saw that for iOS you added this file type the `plaintextFormat`. Let me know if my assumption is correct and I can create a PR if needed.

[test.txt](https://github.com/superlistapp/super_native_extensions/files/10833323/test.txt)

**Comment by knopp** [comment]
Sorry, this is a bit underdocumented, I'll need to fix this.

`Formats.plainText` is meant for things like text snippets, mostly when copying and pasting text. Which means on some platforms that involves conversion from/to platform native format (i.e. UTF-16 on windows)

`Formats.utf8Text` is meant for dropped text files. The difference here is that in this case no conversion will be done, you get the stream for exact file content.

The name is a bit misleading though, because at no point does `super_drag_and_drop` check if the file is really utf-8. That would be a responsibility of whoever is receiving the stream. I'm maybe leaning towards renaming this to `Formats.plainTextFile`.

**Comment by remonh87** [comment]
Thanks, I switched to utf8Text which worked, the fact that it didn't convert was clear to me because it was in the code comment and the stream returns a Uuint8List instead of String.  T

he name change would make things more clear for the `super_drag_and_drop`,  but I noticed the same datatype is used for `super_clip_board` and not sure if the name change would make things less clear for that package.

Maybe adding a code comment for `plainText` would help already for example: 
```dart
/// Use this format for text snippets, like copying and pasting text. 
///
/// For text files use [utf8Text].
static const plainText = SimpleValueFormat<String>(
```

**Comment by knopp** [comment]
This can be closed. There is now `StandardFormats.plainTextFile` type.
